module.exports = {
  content: [
    './_includes/**/*.{html,md,js}',
    './_layouts/**/*.{html,md,js}',
    './_*/**/*.{html,md,js}',
    '!./_site/**/*.{html,md,js}',
    './*.{html,md,js}'
  ],
  theme: {
    container: {
      center: true,
      padding: '5%',
    },
    extend: {
      backgroundImage: {
        'hero-home': "url('https://source.unsplash.com/8Ogfqvw15Rg/1600x1600')",
        'meta': "url('https://as2.ftcdn.net/v2/jpg/03/92/52/89/1000_F_392528902_B3j7Wfv3mS9DdZDKTXzQgx1uwxharGtt.jpg')",
        'char1': "url('16-Free-Vector-User-Avatar-Icons.png')",
      },
      spacing: {
        '1p': '1%',
        '2p': '2%',
        '3p': '3%',
        '5p': '5%',
        '6p': '6%',
        '7p': '7%',
        '8p': '8%',
        '10p': '10%',
        '15p': '15%',
        '16p': '16%',
        '17p': '17%',
        '18p': '18%',
        '19p': '19%',
        '20p': '20%',
        '25p': '25%',
        '30p': '30%',
        '40p': '40%',
        '42p': '42%',
        '45p': '45%',
        '50p': '50%',
        '60p': '60%',
        '70p': '70%',
      },
      aspectRatio: {
        'portrait': '3/4',
        'portrait-tall': '3/5',
        'landscape': '4/3',
      },
      height: {
        '2vh': '2vh',
        '10vh': '10vh',
        '40vh': '40vh',
        '50vh': '50vh',
        '60vh': '60vh',
        '70vh': '70vh',
        '80vh': '80vh',
        '90vh': '90vh',
      },
      borderWidth: {
        '5': '5px',
        '16': '16px',
      },
      colors: {
        amGreen: '#70836F',
        amOffWhite: '#F6F6F6',
        amLiteGrey: '#E8E8E8',
        amGrey: '#A0A09F',
        amMedGrey: '#605E5D',
        amDkGrey: '#2E2E2E',
        amMedBlue: '#325274',
        amDkBlue: '#212F43',
        mediaBg: '#e3edf7',
        mediaTitle: '#4d4d4d',
        mediaProgress: '#0987f6',
      },
      fontFamily: {
        cinzel: ['Cinzel', 'serif'],
        openSans: ['Open Sans', 'sans-serif'],
        workSans: ['Work Sans', 'sans-serif'],
        roboto: ['Roboto Slab', 'serif'],
        // serif: ['Merriweather', 'serif'],
        // nunito: ['Nunito Sans', 'sans-serif'],
        // mont: ['Montserrat', 'sans-serif'],
        // sans: ['Figtree', 'sans-serif'],
        // lora: ['Lora', 'serif'],
      }
    },
  },
  plugins: [require('tailwind-scrollbar-hide')],
  plugins: [require('tailwindcss-unsplash')],
}
